name: 'Main actions file'
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Build-Typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy everything to action folder
        run: cp -rf ./package.json ./package-lock.json ./tsconfig.json ./src ./.github/workflows/build-action
      - name: Build
        uses: ./.github/workflows/build-action